name: OC-Login
description: OpenShift CLI Login on OpenShift

inputs:
  openshift_token:
    description: 'Openshift Token'
    required: true
  namespace:
    description: 'Openshift Namespace'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Install oc'
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4

    - name: 'Authenticate and set context'
      uses: redhat-actions/oc-login@v1
      env:
        OPENSHIFT_NAMESPACE: 'domigmail-dev'
      with:
        openshift_server_url: https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443
        openshift_token: ${{ inputs.openshift_token }}
        insecure_skip_tls_verify: true
        namespace: ${{ inputs.namespace }}
