name: Pull-Request Build

env:
  TZ: "Europe/Zurich"

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#
#      - name: 'Login into openshift'
#        uses: ./.github/actions/oc-login

      - name: 'Install oc'
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: 'Authenticate and set context'
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: 'domigmail-dev'
        with:
          openshift_server_url: https://main-domigmail-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
#          openshift_username: ${{ secrets.OPENSHIFT_USER }}
#          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: 'test login'
        run: oc project
