name: Pull-Request Build

env:
  TZ: "Europe/Zurich"

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Login into openshift'
        uses: ./.github/actions/oc-login
        with:
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: 'list projects'
        run: oc project
